<template>
  <Layout class="sans">
    <br />

    <h2 style="margin-top:3rem; " class="is-size-5">
      Work
      <span class="has-text-grey">/ All</span>
    </h2>
    <div class="columns is-size-5">
      <div class="column is-7">
       <p> A bit empty now, browse my  <a href="https://github.com/padamsethia">Github </a></p> 
      </div>
    </div>
  </Layout>
</template>


<script>
export default {
  metaInfo: {
    title: 'Work'
  }
}
</script>
